guiatta/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'guiatta.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'', include('main.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^adminek/', include(admin.site.urls)),
)

main/urls.py
from django.conf.urls import *
from views import *
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView
from models import *
from django.views.decorators.cache import never_cache

urlpatterns = patterns('',
    url(r'^$', index),
    url(r'^login/$', 'django.contrib.auth.views.login', {
                'template_name': 'main/login.html'}),
    url(r'^interfaces/$', login_required(never_cache(InterfacesView.as_view() ), ) ),
    url(r'^create_interfaces/$', login_required(CreateInterfacesView.as_view())),
    url(r'^update_interfaces/(?P<pk>\d+)/$', login_required(UpdateInterfacesView.as_view())),
    url(r'^delete_interfaces/(?P<pk>\d+)/$', login_required(DeleteInterfacesView.as_view())),
    url(r'^refresh_configs/$', login_required(refresh_router_configs) ),
    url(r'^bridges/$', login_required(never_cache(BridgeView.as_view() ), ) ),
    url(r'^create_bridges/$', login_required(CreateBridgeView.as_view())),
    url(r'^update_bridges/(?P<pk>\d+)/$', login_required(UpdateBridgeView.as_view())),
    url(r'^delete_bridges/(?P<pk>\d+)/$', login_required(DeleteBridgeView.as_view())),
    url(r'^logout/$', user_logout, name='logout'),
    url(r'^routers/$', login_required(RoutersView.as_view())),
    url(r'^create_routers/$', login_required(CreateRoutersView.as_view())),
    url(r'^update_routers/(?P<pk>\d+)/$', login_required(UpdateRoutersView.as_view())),
    url(r'^delete_routers/(?P<pk>\d+)/$', login_required(DeleteRoutersView.as_view())),
    url(r'^upload_config/$', login_required(uploadConfig)),
    url(r'^configtest/$', testview)
)

main/models.py
from django.db import models
import django.contrib.auth.hashers

# Create your models here.

class Routers(models.Model):
    name = models.CharField(max_length=200)
    ip = models.IPAddressField()
    user = models.CharField(max_length=100)
    password = models.CharField(max_length=50)
    selected = models.BooleanField(default=0)

    def __unicode__(self):
        return self.name

class Bridge(models.Model):
    router_id = models.ForeignKey(Routers)
    name = models.CharField(max_length=100)
    ip =  models.CharField(max_length=200, blank=True, null=True)
    hw_id = models.CharField(max_length=17, blank=True, null=True)
    stp_enabled = models.CharField(max_length=100, blank=True, null=True)
    description = models.CharField(max_length=150, blank=True, null=True)

    def __unicode__(self):
        return self.name

class Interfaces(models.Model):
    router_id = models.ForeignKey(Routers)
    name = models.CharField(max_length=50)
    ip = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=200, blank=True, null=True)
    hw_id = models.CharField(max_length=17)

    def __unicode__(self):
        return self.name

class Version(models.Model):
    #tutaj prawdopodobnie jedno pole ktore bedzie sluzylo jako backup versji
    pole = models.CharField(max_length=200)

class Arp(models.Model):
    ip = models.IPAddressField()
    hw_type = models.CharField(max_length=50)
    hw_address = models.CharField(max_length=17)
    flags = models.CharField(max_length=20)
    masks = models.CharField(max_length=20)
    iface = models.CharField(max_length=20)

class Router_Date(models.Model):
    #moze sie przyda
    date = models.DateTimeField()

class Hardware(models.Model):
    #podobnie jak wersja
    pole = models.CharField(max_length=200)

class Incoming(models.Model):
    interface = models.CharField(max_length=100)
    action = models.CharField(max_length=100)
    receive = models.CharField(max_length=100)
    dropped = models.CharField(max_length=100)
    overlimit = models.CharField(max_length=100)

from django.db.models.signals import post_delete
from django.dispatch.dispatcher import receiver

class ConfigFile(models.Model):
    file = models.FileField(upload_to='.')
    title = models.CharField(max_length=100)

    def __unicode__(self):
        return self.title

main/forms.py
from django import forms
from django.core.exceptions import ValidationError
from models import *
from django.contrib import admin

class RouterForm(forms.ModelForm):
    class Meta:
        model = Routers
        widgets = {
            'password': forms.PasswordInput(),
        }

class InterfacesInline(admin.TabularInline):
    model = Interfaces

class InterfacesForm(forms.ModelForm):
    class Meta:
        model = Interfaces

class BridgeForm(forms.ModelForm):
    class Meta:
        model = Bridge

class UploadFileForm(forms.ModelForm):
    class Meta:
        model = ConfigFile

main/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpRequest, HttpResponse
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse
from django.views import generic
from django.template import RequestContext
import django.contrib.auth as auth
from django.contrib.auth.decorators import login_required
from forms import *
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.views.decorators.debug import sensitive_variables, sensitive_post_parameters
from django.forms.util import ErrorList
from api import *
import paramiko
from django.views.decorators.cache import cache_control

from models import *

def wrap_error(text, form):
    errors = form._errors.setdefault(forms.forms.NON_FIELD_ERRORS, ErrorList())
    errors.append(text)

def getConfigFile(router):
    r = VyattaRouter(router.ip, router.user, router.password)

    try:
        r.connect()
        r.save_config()
        r.close_connection()
    except StandardError:
        raise

    plik = router.name
    plik += ".cfg"

    try:
        r.dump_config(plik)
    except StandardError:
        raise

    return plik

def put_config(router, plik):
    r = VyattaRouter(router.ip, router.user, router.password)

    try:
        r.put_config(plik)
    except StandardError:
        raise

    try:
        r.connect()
        r.load_config()
        r.close_connection()
    except StandardError:
        raise

def uploadConfig(request):
    # Handle file upload
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            all = ConfigFile.objects.all()
            for a in all:
                a.delete()
            newdoc = ConfigFile(file = request.FILES['file'], title=request.POST['title'])
            newdoc.save()

            routers = Routers.objects.filter(selected=True)
            path = os.path.basename(newdoc.file.url)
            for router in routers:
                put_config(router, path)

            # Redirect to the document list after POST
            return HttpResponseRedirect('/upload_config')
    else:
        form = UploadFileForm() # A empty, unbound form

    selected_list = Routers.objects.filter(selected=1)

    # Render list page with the documents and the form
    return render_to_response(
        'main/upload_config.html',
        {'form': form, 'selected_list': selected_list},
        context_instance=RequestContext(request)
    )

def index(request):
    #menu glowne
    if request.user.is_authenticated():
        return render_to_response('main/index.html', RequestContext(request))
    else:
        return HttpResponseRedirect("/login/")

def user_login(request):
    # Like before, obtain the context for the user's request.
    context = RequestContext(request)

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        username = request.POST['username']
        password = request.POST['password']

        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = auth.authenticate(username=username, password=password)

        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user is not None:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                auth.login(request, user)
                return HttpResponseRedirect('/')
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your guiatta account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print "Invalid login details: {0}, {1}".format(username, password)
            return HttpResponse("Zle dane logowania")

    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render_to_response('main/login.html', {}, context)

@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    auth.logout(request)

    # Take the user back to the homepage.
    return HttpResponseRedirect('/')

def refresh_router_configs(request):
    routers = Routers.objects.all()
    for router in routers:
        try:
            plik = getConfigFile(router)
        except StandardError:
            return HttpResponse("Blad przy pobieraniu configow")

        interfaces = Interfaces.objects.filter(router_id=router)
        bridges = Bridge.objects.filter(router_id=router)

        for interface in interfaces:
            interface.delete()

        for bridge in bridges:
            bridge.delete()

        try:
            filepath = BASE_DIR
            filepath += "/config_files"
            filepath = os.path.join(filepath, plik)
            interfaces = find_ethernet_interfaces(filepath)
            bridges = find_bridges(filepath)
        except StandardError:
            return HttpResponse("Blad przy pobieraniu interfejsow z configow")

        for interface in interfaces:
            i = Interfaces(router_id=router,
                            name=interface['name'],
                            hw_id=interface['mac_address'],
                            ip=interface['ip'],
                            description=interface['description'])

            try:
                i.save()

            except StandardError:
                return HttpResponse("Blad przy zapisywaniu interfejsow do bazy")

        for bridge in bridges:
            b = Bridge(router_id=router,
                       name=bridge['name'],
                       ip=bridge['ip'],
                       stp_enabled=bridge['stp_enabled'],
                       hw_id=bridge['mac'])

            try:
                b.save()

            except StandardError:
                return HttpResponse("Blad przy zapisywaniu bridgy do bazy")

        #return super(CreateRoutersView, self).form_valid(form)
        return HttpResponseRedirect("/routers/")


class InterfacesView(generic.ListView):
    model = Interfaces
    template_name = 'main/interfaces.html'

    def get_context_data(self, **kwargs):
        context = super(InterfacesView, self).get_context_data(**kwargs)
        context['selected_list'] = Routers.objects.filter(selected=1)
        context['interfaces_list'] = Interfaces.objects.order_by('id')
        return context

class CreateInterfacesView(CreateView):
    model = Interfaces
    template_name_suffix = '_create_form'
    success_url = "/interfaces/"
    form_class = InterfacesForm

    def dispatch(self, *args, **kwargs):
        return super(CreateInterfacesView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        router = Routers.objects.get(id=form.instance.router_id.pk)
        i = Interfaces(router_id=router,
                       name=form.instance.name,
                       hw_id=form.instance.hw_id,
                       ip=form.instance.ip,
                       description=form.instance.description)

        i.save()

        update_interface(router, i)
        return HttpResponseRedirect("/interfaces/")

class UpdateInterfacesView(UpdateView):
    model = Interfaces
    template_name_suffix = '_update_form'
    success_url = "/interfaces/"
    form_class = InterfacesForm

    def dispatch(self, *args, **kwargs):
        return super(UpdateInterfacesView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        router = Routers.objects.get(id=self.get_object().router_id.pk)

        try:
            super(UpdateInterfacesView, self).form_valid(form)
        except Exception:
            return HttpResponseRedirect("/interfaces/")

        interface = Interfaces.objects.get(id=self.get_object().pk)
        update_interface(router, interface)
        return HttpResponseRedirect("/interfaces/")

class DeleteInterfacesView(DeleteView):
    model = Interfaces
    template_name_suffix = '_delete_form'
    success_url = "/interfaces/"

    def dispatch(self, *args, **kwargs):
        return super(DeleteInterfacesView, self).dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        router = Routers.objects.get(id=self.get_object().router_id.pk)
        interface = Interfaces.objects.get(id=self.get_object().pk)
        try:
            super(DeleteInterfacesView, self).delete(request, args, kwargs)
        except Exception:
            return HttpResponseRedirect("/interfaces/")
        delete_inerface(router, interface)
        return HttpResponseRedirect("/interfaces/")

class BridgeView(generic.ListView):
    model = Bridge
    template_name = "main/bridges.html"

    def get_context_data(self, **kwargs):
        context = super(BridgeView, self).get_context_data(**kwargs)
        context['selected_list'] = Routers.objects.filter(selected=1)
        context['bridges_list'] = Bridge.objects.order_by('id')
        return context

class CreateBridgeView(CreateView):
    model = Bridge

main/templates/main/bridge_create_form.html
{% extends "main/routers.html" %}

{% block content %}

<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" />
</form>
<a href="/bridges/">Powrot</a>

{% endblock %}

main/templates/main/bridge_delete_form.html
{% extends "main/routers.html" %}

{% block content %}

<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
<a href="/bridges/">Powrot</a>

{% endblock %}

main/templates/main/bridges.html
{% extends "main/index.html" %}
{% block content %}
{% include "main/selected_routers.html" %}
{% if bridges_list %}
    <h2>Bridges:</h2>
    {% for router in selected_list %}
        <table>
        <tr><td>{{ router.name }}&nbsp;<a href="/create_bridges/"><button type="button">+</button></a></td></tr>
        <tr><td></td>
        {% for bridge in bridges_list %}
            {% if bridge.router_id == router %}
                <th> {{ bridge.name }}&nbsp;
                    <a href="/update_bridges/{{ bridge.id }}/"><button type="button">Edit</button></a>&nbsp;
                    <a href="/delete_bridges/{{ bridge.id }}/"><button type="button" onclick="">Delete</button></a></th>
            {% endif %}
        {% endfor %}
        </tr>
        <tr><th>Name:</th>
        {% for bridge in bridges_list %}
            {% if bridge.router_id == router %}
                <td>{{ bridge.name }}</td>
            {% endif %}
        {% endfor %}
        </tr>
        <tr><th>IP</th>
        {% for bridge in bridges_list %}
            {% if bridge.router_id == router %}
                <td>{{ bridge.ip }}</td>
            {% endif %}
        {% endfor %}
        </tr>
        <tr><th>STP</th>
        {% for bridge in bridges_list %}
            {% if bridge.router_id == router %}
                <td>{{ bridge.stp_enabled }}</td>
            {% endif %}
        {% endfor %}
        </tr>
        <tr><th>MAC</th>
        {% for bridge in bridges_list %}
            {% if bridge.router_id == router %}
                <td>{{ bridge.hw_id }}</td>
            {% endif %}
        {% endfor %}
        </tr>
        <tr><th>Description</th>
        {% for bridge in bridges_list %}
            {% if bridge.router_id == router %}
                <td>{{ bridge.description }}</td>
            {% endif %}
        {% endfor %}
        </tr>
        </table><br>
    {% endfor %}
{% else %}
    <p>No bridges are available.</p>
{% endif %}
{% endblock %}

main/templates/main/index.html
<html>
<head>
<link rel="stylesheet" type="text/css" href="/static/main/statics/style.css" />
</head>
<body>
    {% include "main/navigation.html" %}
    {% block content %}
        <h2>Witaj! użytkowniku!</h2>
    {% endblock %}
</body>
</html>

main/templates/main/interfaces.html
{% extends "main/index.html" %}
{% block content %}
{% include "main/selected_routers.html" %}
{% if interfaces_list %}
    <h2>Interfaces:</h2>
    {% for router in selected_list %}
        <table>
        <tr><td>{{ router.name }}&nbsp;<a href="/create_interfaces/"><button type="button">+</button></a></td></tr>
        <tr><td></td>
        {% for interface in interfaces_list %}
            {% if interface.router_id == router %}
                <th> {{ interface.name }}&nbsp;
                    <a href="/update_interfaces/{{ interface.id }}/"><button type="button">Edit</button></a>&nbsp;
                    <a href="/delete_interfaces/{{ interface.id }}/"><button type="button" onclick="">Delete</button></a></th>
            {% endif %}
        {% endfor %}
        </tr>
        <tr><th>IP</th>
        {% for interface in interfaces_list %}
            {% if interface.router_id == router %}
                <td>{{ interface.ip }}</td>
            {% endif %}
        {% endfor %}
        </tr>
        <tr><th>MAC</th>
        {% for interface in interfaces_list %}
            {% if interface.router_id == router %}
                <td>{{ interface.hw_id }}</td>
            {% endif %}
        {% endfor %}
        </tr>
        <tr><th>Description</th>
        {% for interface in interfaces_list %}
            {% if interface.router_id == router %}
                <td>{{ interface.description }}</td>
            {% endif %}
        {% endfor %}
        </tr>
        </table><br>
    {% endfor %}
{% else %}
    <p>No interfaces are available.</p>
{% endif %}
{% endblock %}

main/templates/main/interfaces_create_form.html
{% extends "main/routers.html" %}

{% block content %}

<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" />
</form>
<a href="/interfaces/">Powrot</a>

{% endblock %}

main/templates/main/interfaces_delete_form.html
{% extends "main/routers.html" %}

{% block content %}

<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
<a href="/interfaces/">Powrot</a>

{% endblock %}

main/templates/main/interfaces_update_form.html
{% extends "main/routers.html" %}

{% block content %}

<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
<a href="/interfaces/">Powrot</a>

{% endblock %}

main/templates/main/navigation.html
{% load menu %}
<link rel="stylesheet" type="text/css" href="/static/main/statics/menu.css" />
<div id="topbar">
    <div class="navbar">
        <div class="navbar-side navbar-left"></div>
        <div class="navbar-content">
        {% if user.is_authenticated %}
            <ul id="nav">
                <li><a class="{% navactive request '^$' %}"
                href="/">Start</a></li>

                <li><a class="{% navactive request '^routers/$' %}"
                href="/routers/">Routers</a></li>

                <li><a class="{% navactive request '^interfaces/$' %}"
                href="/interfaces/">Interfaces</a></li>

                <li><a class="{% navactive request '^bridges/$' %}"
                href="/bridges/">Bridges</a></li>

                <li><a class="{% navactive request 'upload_config/$' $}"
                href="/upload_config/">Upload config</a></li>

                <li><a href="/logout/">Logout</a></li>
            </ul>
        {% else %}
            <a href="/login/">Login</a>
        {% endif %}
        </div>
        <div class="navbar-side navbar-right"></div>
    </div>
</div>

main/templates/main/routers.html
{% extends "main/index.html" %}
{% block content %}

    {% if routers_list %}
        <h2>Routers&nbsp;<a href="/refresh_configs/"><button type="button">Refresh</button></a></h2>
        <table>
            <tr>
                <td>Selected</td>
                <td>Name</td>
                <td>IP</td>
                <td>Login</td>
                <td></td><td></td>
            </tr>
        {% for item in routers_list %}
            <tr>
                <td><input type="checkbox" disabled="" {% if item.selected %}checked {% endif %} /></td>
                <td>{{ item.name }}</td>
                <td>{{ item.ip }}</td>
                <td>{{ item.user }}</td>
                <td><a href="/update_routers/{{ item.id }}/">Edit</a>&nbsp&nbsp</td>
                <td><a href="/delete_routers/{{ item.id }}/">Delete</a></td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <p>No routers stored in database. Add routers.</p>
    {% endif %}
    </ br><a href="/create_routers/">Add new</a>

{% endblock %}

main/templates/main/routers_create_form.html
{% extends "main/routers.html" %}

{% block content %}

<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" />
</form>
<a href="/routers/">Powrot</a>

{% endblock %}

main/templates/main/routers_update_form.html
{% extends "main/routers.html" %}

{% block content %}

<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
<a href="/routers/">Powrot</a>

{% endblock %}

main/templates/main/selected_routers.html
    {% if selected_list %}
        <h2>Selected Routers</h2>
        <table>
            <tr>
                <td>Name</td>
                <td>IP</td>
                <td>Login</td>
            </tr>
        {% for item in selected_list %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.ip }}</td>
                <td>{{ item.user }}</td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <p>No selected routers are available. Add routers.</p>
    {% endif %}
    <a href="/routers/">Edit routers</a>

main/templates/main/upload_config.html
{% extends "main/index.html" %}
{% block content %}
{% include "main/selected_routers.html" %}
<!-- Upload form. Note enctype attribute! -->
        <h2>Upload config for selected routers::</h2>
        <form action="/upload_config/" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>
            <p>
                {{ form.file.errors }}
                {{ form.as_p }}
            </p>
            <p><input type="submit" value="Upload" /></p>
        </form>

{% endblock %}